/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alimundo.requisicionmateriales;

import java.awt.Cursor;

/**
 *
 * @author AdminSrv
 */
public class Ayuda extends javax.swing.JDialog {

    /**
     * Creates new form Ayuda
     */
    public Ayuda() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setModal(true);
        new CargarComponentes().addTextField(this.labelversionsql, "EXEC spu_versistemarequisicion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelcerrar = new javax.swing.JLabel();
        labeltitulo1 = new javax.swing.JLabel();
        labeltitulo = new javax.swing.JLabel();
        labelversion = new javax.swing.JLabel();
        labelversionsql = new javax.swing.JLabel();
        labelcopyright = new javax.swing.JLabel();
        copyright1 = new javax.swing.JLabel();
        labeldesarrollo1 = new javax.swing.JLabel();
        labeldesarrollo2 = new javax.swing.JLabel();
        labeldesarrollo3 = new javax.swing.JLabel();
        labeldesarrollodpto = new javax.swing.JLabel();
        labeldesarrolloprogramador = new javax.swing.JLabel();
        labeldesarrollobd = new javax.swing.JLabel();
        labeltelegram = new javax.swing.JLabel();
        labelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(390, 259));
        setMinimumSize(new java.awt.Dimension(390, 259));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(390, 259));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngs32X32/cancel.png"))); // NOI18N
        labelcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelcerrarMouseClicked(evt);
            }
        });
        getContentPane().add(labelcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 4, -1, -1));

        labeltitulo1.setBackground(new java.awt.Color(255, 255, 255));
        labeltitulo1.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        labeltitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltitulo1.setText("INFORMACIÓN");
        labeltitulo1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labeltitulo1.setOpaque(true);
        getContentPane().add(labeltitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        labeltitulo.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        labeltitulo.setText("Módulo Requisición ALIMUNDO C.A.");
        getContentPane().add(labeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 340, 30));

        labelversion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelversion.setText("Versión:");
        getContentPane().add(labelversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        labelversionsql.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        labelversionsql.setForeground(new java.awt.Color(0, 102, 204));
        labelversionsql.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(labelversionsql, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 70, 20));

        labelcopyright.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelcopyright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pngs32X32/copyright.png"))); // NOI18N
        getContentPane().add(labelcopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        copyright1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        copyright1.setText("copyright 2022");
        getContentPane().add(copyright1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        labeldesarrollo1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labeldesarrollo1.setText("Diseño de Base de Datos:");
        getContentPane().add(labeldesarrollo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, -1));

        labeldesarrollo2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labeldesarrollo2.setText("Diseño y Programación:");
        getContentPane().add(labeldesarrollo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 170, -1));

        labeldesarrollo3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labeldesarrollo3.setText("Desarrollado por el Departamento de:");
        getContentPane().add(labeldesarrollo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 270, -1));

        labeldesarrollodpto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labeldesarrollodpto.setText("Información y Técnologia");
        getContentPane().add(labeldesarrollodpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, -1));

        labeldesarrolloprogramador.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labeldesarrolloprogramador.setText("Christian Zerpa");
        getContentPane().add(labeldesarrolloprogramador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, -1));

        labeldesarrollobd.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labeldesarrollobd.setText("Christian Zerpa");
        getContentPane().add(labeldesarrollobd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 130, -1));

        labeltelegram.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        labeltelegram.setText("Telegram: @ChristianZerpa");
        getContentPane().add(labeltelegram, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        labelfondo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(labelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcerrarMouseClicked
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        this.dispose();
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_labelcerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ayuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyright1;
    private javax.swing.JLabel labelcerrar;
    private javax.swing.JLabel labelcopyright;
    private javax.swing.JLabel labeldesarrollo1;
    private javax.swing.JLabel labeldesarrollo2;
    private javax.swing.JLabel labeldesarrollo3;
    private javax.swing.JLabel labeldesarrollobd;
    private javax.swing.JLabel labeldesarrollodpto;
    private javax.swing.JLabel labeldesarrolloprogramador;
    private javax.swing.JLabel labelfondo;
    private javax.swing.JLabel labeltelegram;
    private javax.swing.JLabel labeltitulo;
    private javax.swing.JLabel labeltitulo1;
    private javax.swing.JLabel labelversion;
    private javax.swing.JLabel labelversionsql;
    // End of variables declaration//GEN-END:variables
}
